apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github-mcp-remote.yaml
  - f5-bigip-mcp.yaml
  - f5-wrapper-deployment.yaml
  - fortigate-mcp.yaml
  - fortigate-mcp-deployment.yaml
  - enterprise-agentgateway-bridge.yaml
  - vault-mcp.yaml
  - vault-mcp-deployment.yaml
  - moat-mcp.yaml

commonLabels:
  app.kubernetes.io/name: kagent-tool-servers
  app.kubernetes.io/component: remote-mcp

namespace: kagent
