apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentregistry
  namespace: argocd
spec:
  project: default
  destination:
    namespace: agentregistry
    server: https://kubernetes.default.svc
  source:
    repoURL: us-docker.pkg.dev/agentregistry/enterprise/helm
    chart: agentregistry-enterprise
    targetRevision: 0.0.12
    helm:
      valuesObject:
        image:
          tag: "v0.0.12"
        config:
          enableAnonymousAuth: "true"
        aws:
          enabled: false
        service:
          type: ClusterIP
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: agentregistry-agentregistry-enterprise
      jsonPointers:
        - /spec/template/spec/containers/0/livenessProbe
        - /spec/template/spec/containers/0/readinessProbe
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
