apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enterprise-agentgateway
  namespace: argocd
spec:
  destination:
    namespace: agentgateway-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: enterprise-agentgateway
    repoURL: us-docker.pkg.dev/solo-public/enterprise-agentgateway-helm/charts
    targetRevision: v2.2.0-rc.5
    helm:
      valuesObject:
        enableAgentgateway: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
