apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enterprise-agentgateway-crds-helm
  namespace: argocd
spec:
  project: default
  destination:
    namespace: agentgateway-system
    server: https://kubernetes.default.svc
  source:
    repoURL: us-docker.pkg.dev/solo-public/enterprise-agentgateway/charts
    chart: enterprise-agentgateway-crds
    targetRevision: v2.2.0
    helm:
      releaseName: enterprise-agentgateway-crds
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
