apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enterprise-agentgateway-helm
  namespace: argocd
spec:
  project: default
  destination:
    namespace: agentgateway-system
    server: https://kubernetes.default.svc
  source:
    repoURL: us-docker.pkg.dev/solo-public/enterprise-agentgateway/charts
    chart: enterprise-agentgateway
    targetRevision: v2.3.0-beta.8
    helm:
      valuesObject:
        enableAgentgateway: true
        licensing:
          createSecret: false
          secretName: enterprise-agentgateway-license
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
