apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent
  namespace: argocd
spec:
  destination:
    namespace: kagent
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kagent-enterprise
    repoURL: us-docker.pkg.dev/solo-public/kagent-enterprise-helm/charts
    targetRevision: 0.3.12
    helm:
      valuesObject:
        licensing:
          createSecret: false
          secretName: kagent-enterprise-license
        providers:
          default: openAI
          openAI:
            apiKeySecretRef: kagent-openai
            apiKeySecretKey: OPENAI_API_KEY
        otel:
          tracing:
            enabled: true
            exporter:
              otlp:
                endpoint: solo-enterprise-telemetry-collector.kagent.svc.cluster.local:4317
                insecure: true
        controller:
          enabled: true
        kmcp:
          enabled: true
        kagent-tools:
          enabled: true
          tools:
            grafana-mcp:
              enabled: true
            querydoc:
              enabled: true
        agents:
          k8s-agent:
            enabled: false
          kgateway-agent:
            enabled: true
          helm-agent:
            enabled: true
          observability-agent:
            enabled: false
          istio-agent:
            enabled: true
          cilium-crd-agent:
            enabled: true
          argo-rollouts-conversion-agent:
            enabled: true
          promql-agent:
            enabled: true
  ignoreDifferences:
  - group: kagent.dev
    kind: ModelConfig
    name: default-model-config
    jsonPointers:
    - /spec/model
    - /spec/openAI
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
