apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - agentgateway-secrets.yaml
  - kagent-secrets.yaml

commonLabels:
  app.kubernetes.io/name: vault-external-secrets
  app.kubernetes.io/component: secret-management
