apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.29.1
    helm:
      valuesObject:
        global:
          openshift: false
        server:
          enabled: true
          image:
            repository: hashicorp/vault
            tag: 1.18.4
          standalone:
            enabled: true
            config: |
              ui = true
              listener "tcp" {
                tls_disable = 1
                address     = "[::]:8200"
              }
              storage "file" {
                path = "/vault/data"
              }
          dataStorage:
            enabled: true
            size: 10Gi
          service:
            type: NodePort
            nodePort: 30820
          readinessProbe:
            enabled: true
            path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m
        ui:
          enabled: true
        injector:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
