apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: agentgateway-system
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
    exporters:
      otlphttp/solo:
        endpoint: grpc://solo-enterprise-telemetry-collector.agentgateway-system.svc.cluster.local:4317
      otlphttp/langfuse:
        endpoint: http://172.16.10.176:3000/api/public/otel
        headers:
          Authorization: "Basic cGstbGYtZDU5ODE0NzktM2E4Ny00YmRiLThiOTQtMjFlMzM0MjM0NzEzOnNrLWxmLTg4MzYyMGRkLWJmZjAtNDFhMC05NDY5LWZmZjBkYmQ3MTMyMw=="
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlphttp/solo, otlphttp/langfuse]