apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auth-proxy-script.yaml
  - auth-proxy-deployment.yaml

commonLabels:
  app.kubernetes.io/name: khook-auth-proxy
  app.kubernetes.io/component: auth-proxy
