apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s-agent.yaml
  - compliance-incident-agent.yaml
  - github-issues-agent.yaml
  - github-pr-agent.yaml
  - f5-bigip-agent.yaml
  - fortigate-agent.yaml
  - vault-agent.yaml
  - ansible-infra-agent.yaml
  - cilium-crd-agent.yaml
  - k8s-f5-agent.yaml
  - moat-sandbox-coder.yaml

commonLabels:
  app.kubernetes.io/name: kagent-agents
  app.kubernetes.io/component: agents

namespace: kagent
