apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: claude-model-config
  namespace: kagent
spec:
  apiKeySecret: anthropic-api-keys
  apiKeySecretKey: ANTHROPIC_API_KEY
  model: claude-opus-4-6
  provider: Anthropic
  anthropic: {}
