apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: llm-agentgateway
  namespace: kagent
spec:
  apiKeySecret: kagent-openai
  apiKeySecretKey: OPENAI_API_KEY
  provider: OpenAI
  model: gpt-5.2-2025-12-11
  openAI:
    baseUrl: "http://172.16.20.120:8080/openai"
